FROM node:20.17.0-alpine

RUN apk add --no-cache bash
RUN npm i -g @nestjs/cli typescript ts-node

COPY package*.json /usr/src/app/
COPY tsconfig*.json /usr/src/app/
COPY .env.example /usr/src/app/
COPY src /usr/src/app/src
COPY test /usr/src/app/test
RUN cd /usr/src/app && npm install

COPY wait-for-it.sh /opt/wait-for-it.sh
RUN chmod +x /opt/wait-for-it.sh
COPY startup.relational.test.sh /opt/startup.relational.test.sh
RUN chmod +x /opt/startup.relational.test.sh
RUN sed -i 's/\r//g' /opt/wait-for-it.sh
RUN sed -i 's/\r//g' /opt/startup.relational.test.sh

WORKDIR /usr/src/app
RUN cp .env.example .env.prod
# RUN npm run build

CMD ["/opt/startup.relational.test.sh"]
